version: '3'
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5001
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "5001:5001"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - MONGODB_URI=mongodb://mongo:27017/credit_risk_db
      - PORT=5001
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
